# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'VKProject1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKProject1
pod 'Alamofire', '~> 5.4'
pod "RxRealm"
pod 'Kingfisher', '~> 7.0'
pod 'Firebase/Database'
pod "PromiseKit", "~> 6.8"
pod 'SwiftKeychainWrapper'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
pod 'Firebase/InAppMessaging'
pod 'Firebase/Database'
end

